package cn.ac.iie.RPMod.fidouafclient.msg;

public enum UAFIntentType {
		DISCOVER,
		DISCOVER_RESULT,
		CHECK_POLICY,
		CHECK_POLICY_RESULT,
		UAF_OPERATION,
		UAF_OPERATION_RESULT,
		UAF_OPERATION_COMPLETION_STATUS
}
